import os
import yfinance as yf
from datetime import datetime, timedelta
import pandas as pd
from flask import Flask
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, scoped_session

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///stocks.db"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

from models import db, Company, FinancialReport, StockPrice
from market_data import fetch_market_data, persist_market_data

db.init_app(app)

SAMPLE_TICKERS = [
    "AAPL",
    "MSFT",
    "GOOGL",
    "AMZN",
    "NVDA",
    "META",
    "TSLA",
    "BRK.B",
    "LLY",
    "AVGO",
    "V",
    "JPM",
    "WMT",
    "XOM",
    "MA",
    "UNH",
    "PG",
    "JNJ",
    "HD",
    "ORCL",
    "MRK",
    "COST",
    "ABBV",
    "KO",
    "PEP",
    "CVX",
    "BAC",
    "TMO",
    "MCD",
    "DIS",
    "CSCO",
    "ABT",
    "ACN",
    "WFC",
    "VZ",
    "ADBE",
    "CRM",
    "NKE",
    "INTC",
    "TXN",
    "NEE",
    "PM",
    "BMY",
    "UNP",
    "RTX",
    "HON",
    "QCOM",
    "LOW",
    "IBM",
    "SBUX",
    "AMD",
    "GS",
    "CAT",
    "BLK",
    "INTU",
    "DE",
    "MDLZ",
    "AMGN",
    "GILD",
    "SPGI",
    "ADP",
    "CVS",
    "LRCX",
    "ISRG",
    "VRTX",
    "REGN",
    "SYK",
    "PLD",
    "CI",
    "MMC",
    "TJX",
    "CB",
    "ZTS",
    "MO",
    "SCHW",
    "ETN",
    "CME",
    "SO",
    "BDX",
    "DUK",
    "CL",
    "PNC",
    "APD",
    "ICE",
    "NSC",
    "MCK",
    "EOG",
    "ITW",
    "FIS",
    "SHW",
    "WM",
    "GD",
    "AON",
    "BSX",
    "EL",
    "EMR",
    "KLAC",
    "MCO",
    "AXP",
    "USB",
    "TFC",
    "COF",
    "MS",
    "SCHD",
    "SPY",
    "QQQ",
    "IWM",
    "VTI",
    "VOO",
    "VGT",
    "XLK",
    "XLF",
    "XLE",
    "XLV",
    "XLI",
    "XLC",
    "XLY",
    "XLP",
    "XLB",
    "XLRE",
    "AGG",
    "BND",
    "TLT",
    "GLD",
    "SLV",
    "USO",
    "UNG",
    "DBC",
    "VNQ",
    "IYR",
    "EFA",
    "EEM",
    "VWO",
    "IEMG",
    "IEFA",
    "IJH",
    "IWM",
    "IWF",
    "IWD",
    "IWR",
    "TQQQ",
    "SQQQ",
    "FAS",
    "FAZ",
    "SOXL",
    "SOXS",
    "TNA",
    "TZA",
    "UDOW",
    "SDOW",
    "AIG",
    "MET",
    "PRU",
    "AFL",
    "TRV",
    "C",
    "SYY",
    "MDT",
    "SYK",
    "BSX",
    "ABMD",
    "ALGN",
    "ANSS",
    "ATVI",
    "CDNS",
    "CTAS",
    "DLTR",
    "DXCM",
    "EW",
    "FANG",
    "IDXX",
    "ILMN",
    "INTU",
    "ISRG",
    "LULU",
    "MAR",
    "MELI",
    "MTCH",
    "OKTA",
    "PANW",
    "PDD",
    "PYPL",
    "RIVN",
    "ROKU",
    "SNPS",
    "TEAM",
    "TMUS",
    "TTWO",
    "UBER",
    "VEEV",
    "WDAY",
    "ZM",
    "ZS",
    "DDOG",
    "CRWD",
    "NET",
    "SNOW",
    "HUBS",
    "ESTC",
    "DBX",
    "GTLB",
    "APP",
    "DLO",
    "FVRR",
    "GLBE",
    "MAPS",
    "OUST",
    "PINS",
    "RBLX",
    "U",
    "BILL",
    "BKR",
    "CE",
    "CPRT",
    "CSGP",
    "CTVA",
    "CZR",
    "DHI",
    "DOW",
    "DXR",
    "EBAY",
    "ELV",
    "ENPH",
    "EPAM",
    "EQT",
    "ES",
    "ETSY",
    "EVRG",
    "EXC",
    "EXPE",
    "EXR",
    "F",
    "FAST",
    "FFIV",
    "FICO",
    "FND",
    "FOXA",
    "FRC",
    "FSLR",
    "FTNT",
    "GE",
    "GNRC",
    "HAL",
    "HBAN",
    "HCA",
    "HES",
    "HII",
    "HOLX",
    "HPQ",
    "HUM",
    "IT",
    "JBHT",
    "JCI",
    "JKHY",
    "KEYS",
    "KHC",
    "KMB",
    "KMI",
    "KO",
    "KR",
    "LHX",
    "LH",
    "LVS",
    "LYB",
    "MCHP",
    "MCY",
    "MGM",
    "MHK",
    "MIC",
    "MKC",
    "MLM",
    "MMC",
    "MOH",
    "MPWR",
    "MRNA",
    "MSCI",
    "MTD",
    "MU",
    "NEM",
    "NHI",
    "NOC",
    "NOV",
    "NRG",
    "NSC",
    "NTAP",
    "NTRS",
    "NUE",
    "NVR",
    "ODFL",
    "OXY",
    "PAYC",
    "PCAR",
    "PEAK",
    "PH",
    "PHM",
    "PKG",
    "PLTR",
    "PNR",
    "PNW",
    "POOL",
    "PPG",
    "PTC",
    "PWR",
    "RAI",
    "RMD",
    "ROK",
    "ROL",
    "RSG",
    "RTX",
    "SBAC",
    "SIVB",
    "SJM",
    "SLB",
    "SNA",
    "SPG",
    "STZ",
    "SWK",
    "TDG",
    "TER",
    "TT",
    "TYL",
    "ULTA",
    "URI",
    "VLO",
    "VMC",
    "VRSK",
    "VTR",
    "WAB",
    "WAT",
    "WEC",
    "WELL",
    "WMB",
    "WST",
    "X",
    "XYL",
    "YUM",
    "ZBH",
    "ZION",
    "A",
    "AA",
    "AAL",
    "AAPL",
    "ABNB",
    "ACGL",
    "ACM",
    "ADC",
    "AEIS",
    "AEP",
    "AER",
    "AG",
    "AGNC",
    "AGCO",
    "AIV",
    "AKAM",
    "ALB",
    "ALE",
    "ALGM",
    "ALK",
    "ALL",
    "ALLY",
    "AMAT",
    "AMC",
    "AMED",
    "AMGN",
    "AMKR",
    "AMP",
    "AMRN",
    "AMT",
    "AMZN",
    "AN",
    "ANET",
    "ANF",
    "AON",
    "APA",
    "APG",
    "APH",
    "AR",
    "ARCH",
    "ARW",
    "ASGN",
    "ASH",
    "ASML",
    "ATO",
    "ATR",
    "AVB",
    "AVY",
    "AWK",
    "AZO",
    "BA",
    "BABA",
    "BAC",
    "BALL",
    "BAX",
    "BB",
    "BBY",
    "BC",
    "BCO",
    "BCRX",
    "BDX",
    "BEN",
    "BHF",
    "BHP",
    "BIIB",
    "BIO",
    "BJ",
    "BK",
    "BKH",
    "BKR",
    "BLK",
    "BLL",
    "BMY",
    "BNH",
    "BNS",
    "BOH",
    "BOKF",
    "BR",
    "BRX",
    "BSX",
    "BTU",
    "BUD",
    "BUR",
    "BWA",
    "BXP",
    "CAG",
    "CAH",
    "CALM",
    "CAT",
    "CB",
    "CBRE",
    "CBSH",
    "CE",
    "CHD",
    "CHRW",
    "CHTR",
    "CI",
    "CINF",
    "CL",
    "CLF",
    "CLX",
    "CMA",
    "CMCSA",
    "CME",
    "CMG",
    "CMI",
    "CMS",
    "CNC",
    "CNP",
    "COF",
    "COHR",
    "COLB",
    "COLM",
    "COO",
    "COP",
    "COST",
    "COTY",
    "CP",
    "CPE",
    "CR",
    "CREE",
    "CRH",
    "CRS",
    "CS",
    "CSCO",
    "CSX",
    "CTAS",
    "CTSH",
    "CTVA",
    "CVS",
    "CVX",
    "CZR",
    "D",
    "DAL",
    "DAN",
    "DASH",
    "DAVA",
    "DB",
    "DBD",
    "DBX",
    "DCI",
    "DCP",
    "DE",
    "DELL",
    "DHI",
    "DHR",
    "DIS",
    "DISCA",
    "DISH",
    "DKNG",
    "DLR",
    "DLY",
    "DNB",
    "DNR",
    "DOCU",
    "DOOR",
    "DOW",
    "DPZ",
    "DRI",
    "DT",
    "DTE",
    "DUK",
    "DVA",
    "DVN",
    "DWDP",
    "DXC",
    "EA",
    "EAT",
    "EBAY",
    "EBR",
    "ECL",
    "ED",
    "EFX",
    "EGP",
    "EL",
    "ELAN",
    "EMN",
    "EMR",
    "ENB",
    "EOG",
    "EPAM",
    "EPC",
    "EQT",
    "ES",
    "ETN",
    "ETR",
    "EVR",
    "EVRG",
    "EXC",
    "EXPD",
    "EXPE",
    "EXR",
    "F",
    "FANG",
    "FAST",
    "FB",
    "FCF",
    "FCX",
    "FDX",
    "FE",
    "FFIV",
    "FICO",
    "FIS",
    "FISV",
    "FITB",
    "FL",
    "FMC",
    "FOR",
    "FOX",
    "FPF",
    "FR",
    "FRC",
    "FREQ",
    "FRT",
    "FSK",
    "FSLR",
    "FTNT",
    "FTR",
    "FTV",
    "G",
    "GCI",
    "GD",
    "GDDY",
    "GE",
    "GILD",
    "GIS",
    "GL",
    "GLW",
    "GM",
    "GNTX",
    "GOLD",
    "GOOG",
    "GOOGL",
    "GPC",
    "GPN",
    "GPS",
    "GRA",
    "GRMN",
    "GS",
    "GWW",
    "HAL",
    "HBI",
    "HCA",
    "HCC",
    "HCW",
    "HD",
    "HDI",
    "HE",
    "HEES",
    "HES",
    "HIG",
    "HII",
    "HLT",
    "HMC",
    "HMW",
    "HOMB",
    "HON",
    "HP",
    "HPE",
    "HPQ",
    "HRL",
    "HRTB",
    "HSIC",
    "HST",
    "HSY",
    "HUM",
    "HWM",
    "HXL",
    "HY",
    "I",
    "IBM",
    "ICE",
    "ICF",
    "ICHR",
    "IDXX",
    "IEX",
    "IFF",
    "ILMN",
    "INCY",
    "INFO",
    "INFY",
    "INSP",
    "INTC",
    "INTU",
    "IONS",
    "IP",
    "IPG",
    "IQV",
    "IR",
    "IRM",
    "ISRG",
    "IT",
    "ITW",
    "IVZ",
    "JBHT",
    "JCI",
    "JCOM",
    "JD",
    "JEF",
    "JKHY",
    "JLL",
    "JNJ",
    "JPM",
    "JWN",
    "K",
    "KAI",
    "KDP",
    "KEY",
    "KEYS",
    "KHC",
    "KIM",
    "KMB",
    "KMI",
    "KMX",
    "KNX",
    "KO",
    "KODK",
    "KOF",
    "KR",
    "KRC",
    "KSS",
    "KT",
    "L",
    "LAZ",
    "LDOS",
    "LEG",
    "LEN",
    "LII",
    "LLY",
    "LMT",
    "LNC",
    "LNT",
    "LOW",
    "LRCX",
    "LSCC",
    "LULU",
    "LUV",
    "LVS",
    "LYB",
    "LYV",
    "M",
    "MA",
    "MAA",
    "MAC",
    "MAR",
    "MAS",
    "MASI",
    "MCD",
    "MCHP",
    "MCK",
    "MCO",
    "MCS",
    "MD",
    "MDLZ",
    "MDT",
    "MEI",
    "MET",
    "META",
    "MFC",
    "MGM",
    "MHK",
    "MHO",
    "MIC",
    "MKC",
    "MLM",
    "MMC",
    "MMM",
    "MO",
    "MOH",
    "MOS",
    "MPC",
    "MPWR",
    "MRK",
    "MRNA",
    "MRO",
    "MS",
    "MSCI",
    "MSFT",
    "MTB",
    "MTCH",
    "MTD",
    "MU",
    "MUR",
    "MWA",
    "MYY",
    "NAC",
    "NDAQ",
    "NEE",
    "NEM",
    "NEP",
    "NFLX",
    "NFX",
    "NGG",
    "NI",
    "NJR",
    "NKE",
    "NLSN",
    "NMIH",
    "NOC",
    "NOK",
    "NRG",
    "NSC",
    "NTAP",
    "NTRS",
    "NUE",
    "NVDA",
    "NVR",
    "NWS",
    "O",
    "ODFL",
    "OIH",
    "OKE",
    "OMF",
    "ORCL",
    "ORLY",
    "OXY",
    "P",
    "PACC",
    "PACW",
    "PANW",
    "PARA",
    "PCAR",
    "PCG",
    "PCH",
    "PCOR",
    "PCRX",
    "PDD",
    "PEAK",
    "PEG",
    "PENN",
    "PEP",
    "PFE",
    "PFG",
    "PG",
    "PGR",
    "PH",
    "PHM",
    "PKG",
    "PKI",
    "PLD",
    "PLTR",
    "PM",
    "PNC",
    "PNR",
    "PNW",
    "PODD",
    "POOL",
    "PPG",
    "PPL",
    "PRGO",
    "PRU",
    "PSA",
    "PSTG",
    "PTON",
    "PWR",
    "PXD",
    "PZZA",
    "QCOM",
    "QRVO",
    "R",
    "RBA",
    "RCL",
    "RDN",
    "RE",
    "REG",
    "REGN",
    "RF",
    "RHI",
    "RIVN",
    "RL",
    "RMD",
    "RNG",
    "ROK",
    "ROL",
    "ROP",
    "ROST",
    "RPM",
    "RRC",
    "RS",
    "RSG",
    "RTX",
    "RUM",
    "RUT",
    "RVLV",
    "RY",
    "RYAAY",
    "S",
    "SAIA",
    "SAND",
    "SAVE",
    "SBAC",
    "SBNY",
    "SBUX",
    "SCHW",
    "SEDG",
    "SEE",
    "SEIC",
    "SF",
    "SFM",
    "SGEN",
    "SH",
    "SHW",
    "SIFY",
    "SIG",
    "SIRI",
    "SITE",
    "SIVB",
    "SJM",
    "SLB",
    "SLF",
    "SLG",
    "SLS",
    "SMAR",
    "SMCI",
    "SMG",
    "SNA",
    "SNAP",
    "SNPS",
    "SO",
    "SOFI",
    "SOGO",
    "SOLV",
    "SPB",
    "SPG",
    "SPGI",
    "SPLK",
    "SPOT",
    "SPR",
    "SQ",
    "SRCL",
    "SRG",
    "SRI",
    "SSNC",
    "ST",
    "STC",
    "STZ",
    "SU",
    "SUI",
    "SUMN",
    "SWK",
    "SWKS",
    "SYF",
    "SYK",
    "SYNA",
    "TECH",
    "TEL",
    "TER",
    "TFC",
    "TFX",
    "TGT",
    "TISI",
    "TJX",
    "TM",
    "TME",
    "TMUS",
    "TNC",
    "TNET",
    "TOL",
    "TPC",
    "TRGP",
    "TRI",
    "TRMB",
    "TRN",
    "TROW",
    "TRTN",
    "TRV",
    "TSCO",
    "TSLA",
    "TSN",
    "TT",
    "TTCF",
    "TTWO",
    "TWLO",
    "TWTR",
    "TXN",
    "TXT",
    "TYL",
    "U",
    "UAL",
    "UBER",
    "UDR",
    "UHS",
    "ULTA",
    "UMC",
    "UNFI",
    "UNH",
    "UNP",
    "UPS",
    "UPST",
    "URBN",
    "URI",
    "USB",
    "USM",
    "UTHR",
    "V",
    "VEEV",
    "VFC",
    "VIAB",
    "VICI",
    "VLO",
    "VMC",
    "VMW",
    "VNO",
    "VOD",
    "VRSK",
    "VRSN",
    "VRTX",
    "VST",
    "VTRS",
    "VZ",
    "W",
    "WAB",
    "WBA",
    "WBD",
    "WCG",
    "WDC",
    "WDFC",
    "WEC",
    "WELL",
    "WFC",
    "WHR",
    "WIP",
    "WIT",
    "WIX",
    "WKB",
    "WLDN",
    "WM",
    "WMB",
    "WMS",
    "WMT",
    "WPC",
    "WRB",
    "WRI",
    "WSM",
    "WSO",
    "WST",
    "WTW",
    "WU",
    "WVR",
    "WY",
    "WYNN",
    "X",
    "XEL",
    "XOM",
    "XPO",
    "XRAY",
    "XRX",
    "XYL",
    "YELP",
    "YETI",
    "YUM",
    "YUMC",
    "ZBH",
    "ZBRA",
    "ZION",
    "ZM",
    "ZS",
    "ZTO",
]


def get_all_tickers():
    return list(set(SAMPLE_TICKERS))


def download_company_data(ticker, session):
    try:
        ticker_obj = yf.Ticker(ticker)
        info = ticker_obj.info

        company = session.query(Company).filter_by(ticker=ticker).first()
        if not company:
            company = Company(ticker=ticker)
            session.add(company)

        company.name = info.get("shortName") or info.get("longName")
        company.sector = info.get("sector")
        company.industry = info.get("industry")
        company.website_url = info.get("website")
        company.pe_ratio = info.get("trailingPE")
        company.pe_forward = info.get("forwardPE")
        company.market_cap = info.get("marketCap")
        company.debt_to_equity = info.get("debtToEquity")
        company.total_debt = info.get("totalDebt")

        shares = info.get("sharesOutstanding")
        if shares:
            company.shares_outstanding = shares

        session.commit()

        hist = ticker_obj.history(period="2y")
        if not hist.empty:
            existing_dates = {
                sp.date
                for sp in session.query(StockPrice)
                .filter_by(company_id=company.id)
                .all()
            }

            for date, row in hist.iterrows():
                if date.date() not in existing_dates:
                    price = StockPrice(
                        company_id=company.id,
                        date=date.date(),
                        open_price=row["Open"],
                        high=row["High"],
                        low=row["Low"],
                        close=row["Close"],
                        volume=int(row["Volume"]),
                    )
                    session.add(price)

            session.commit()

        financials = ticker_obj.quarterly_financials
        if financials is not None and not financials.empty:
            existing_reports = set()
            for fr in (
                session.query(FinancialReport).filter_by(company_id=company.id).all()
            ):
                existing_reports.add((fr.year, fr.quarter))

            for col in financials.columns:
                if pd.notna(col):
                    date = col
                    year = date.year
                    quarter = (date.month - 1) // 3 + 1

                    # Try to get CAPEX from cashflow
                    capex = None
                    try:
                        cashflow = ticker_obj.cashflow
                        if (
                            cashflow is not None
                            and not cashflow.empty
                            and "Capital Expenditure" in cashflow.index
                        ):
                            # Try to match by quarter first
                            for cf_col in cashflow.columns:
                                cf_date = cf_col
                                cf_quarter = (cf_date.month - 1) // 3 + 1
                                if cf_date.year == year and cf_quarter == quarter:
                                    capex = cashflow.loc["Capital Expenditure", cf_col]
                                    if pd.notna(capex):
                                        break
                            # Fallback: try same year (annual cashflow)
                            if capex is None or pd.isna(capex):
                                for cf_col in cashflow.columns:
                                    cf_date = cf_col
                                    if cf_date.year == year:
                                        capex = cashflow.loc[
                                            "Capital Expenditure", cf_col
                                        ]
                                        if pd.notna(capex):
                                            # Annual CAPEX - estimate quarterly as 1/4
                                            capex = capex / 4
                                            break
                    except:
                        pass

                    if (year, quarter) not in existing_reports:
                        revenue = None
                        opex = None
                        net_income = None

                        try:
                            revenue = (
                                financials.loc["Total Revenue", col]
                                if "Total Revenue" in financials.index
                                else None
                            )
                            opex = (
                                financials.loc["Operating Expense", col]
                                if "Operating Expense" in financials.index
                                else None
                            )
                            net_income = (
                                financials.loc["Net Income", col]
                                if "Net Income" in financials.index
                                else None
                            )
                        except:
                            pass

                        if pd.notna(revenue):
                            report = FinancialReport(
                                company_id=company.id,
                                year=year,
                                quarter=quarter,
                                revenue=revenue,
                                opex=opex,
                                capex=capex,
                                net_income=net_income,
                            )
                            session.add(report)
                    else:
                        # Update existing report with CAPEX if missing
                        existing = (
                            session.query(FinancialReport)
                            .filter_by(
                                company_id=company.id, year=year, quarter=quarter
                            )
                            .first()
                        )
                        if (
                            existing
                            and (existing.capex is None or existing.capex == 0)
                            and capex is not None
                        ):
                            existing.capex = capex
                            session.add(existing)

            session.commit()

        try:
            market_payload = fetch_market_data(ticker)
            persist_market_data(company, session, market_payload, status="success")
            session.commit()
        except Exception as market_error:
            persist_market_data(
                company,
                session,
                {},
                status="failed",
                error_message=str(market_error),
            )
            session.commit()
            print(f"Error downloading market data for {ticker}: {market_error}")

        return True
    except Exception as e:
        print(f"Error downloading {ticker}: {e}")
        return False


def main():
    with app.app_context():
        db.create_all()
        Session = sessionmaker(bind=db.engine)
        session = Session()

        tickers = get_all_tickers()
        print(f"Downloading data for {len(tickers)} companies...")

        for i, ticker in enumerate(tickers):
            print(f"[{i + 1}/{len(tickers)}] Downloading {ticker}...")
            download_company_data(ticker, session)

        print("Download complete!")


if __name__ == "__main__":
    main()
